### ISSUE TITLE
Do not connecting to Postgres and Mongodb

### ISSUE THREAD

**Issue by evgeshaDoc** [dbcodeio/public#316]
The extension does not connect to my Postgres and Mongodb databases, I just keep getting "Failed to load connection" error. The problem is that the other postgres connection works perfectly fine, the version of postgres are the same (16.7) and mongodb is of version 4.0.28.

Please provide the feedback of how I can connect or point the mistake I make. Both DB's are in Docker, here is the compose config

```
monga:
    image: arm64v8/mongo:4.0
    platform: linux/arm64/v8
    container_name: monga
    env_file: "./.env"
    ports:
        - '27017:27017'
    environment:
#        - MONGO_INITDB_DATABASE=${MONGO_DB}
#        - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
#        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
        - MONGO_INITDB_DATABASE=telman
        - MONGO_INITDB_ROOT_USERNAME=telman
        - MONGO_INITDB_ROOT_PASSWORD=telman1234
    volumes:
        # seeding scripts
        - ./mongo-entrypoint/init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        # named volumes
        - monga_vol:/data/db
    networks:
        - telman-dev

 db:
    container_name: db
    image: postgres:16-alpine
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
      POSTGRES_DB: ${POSTGRES_DB:-telman}
    volumes:
      - ./postgres:/data/postgres
    ports:
      - '5432:5432'
    networks:
      - postgres
      - telman-dev
    restart: unless-stopped
```
